In [15]:
import pandas as pd
from pathlib import Path
df = pd.read_csv("../processed/master_dataset.csv")

In [16]:
df.head()

,APD ID,Sequence,Length,is_antibacterial,is_anti_gram_positive,is_anti_gram_negative,is_antifungal,is_antiviral,is_antiparasitic,is_anticancer
0,AP05452,AAAGKHKNKGKKNGKHNGWK,20.0,1,1,1,1,0,0,0
1,AP05433,AAAHKHGHGHGKHKNKGKKN,20.0,1,1,1,1,0,0,0
2,AP01515,AACSDRAHGHICESFKSFCKDSGRNGVKLRANCKKTCGLC,40.0,1,1,1,0,0,0,0
3,AP00612,AAEFPDFYDSEEQMGPHQEAEDEKDRADQRVLTEEEKKELENLAAM...,60.0,1,1,1,0,0,0,0
4,AP01914,AAFRGCWTKNYSPKPCL,17.0,1,1,0,0,0,0,0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5955 entries, 0 to 5954
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   APD ID                 5764 non-null   object
 1   Sequence               5955 non-null   object
 2   Length                 5764 non-null   float64
 3   is_antibacterial       5955 non-null   int64
 4   is_anti_gram_positive  5955 non-null   int64
 5   is_anti_gram_negative  5955 non-null   int64
 6   is_antifungal          5955 non-null   int64
 7   is_antiviral           5955 non-null   int64
 8   is_antiparasitic       5955 non-null   int64
 9   is_anticancer          5955 non-null   int64
dtypes: float64(1), int64(7), object(2)
memory usage: 465.4+ KB

In [18]:
df.describe()

,Length,is_antibacterial,is_anti_gram_positive,is_anti_gram_negative,is_antifungal,is_antiviral,is_antiparasitic,is_anticancer
count,5764.000000,5955.000000,5955.000000,5955.000000,5955.000000,5955.000000,5955.000000,5955.000000
mean,23.894865,0.872376,0.697901,0.747271,0.306297,0.064148,0.058942,0.069689
std,11.253413,0.333699,0.459207,0.434613,0.460993,0.245037,0.235536,0.254644
min,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,21.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,31.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
max,62.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Validate Sequences: Check for 20 Standard Amino Acids

Filter and clean peptide sequences to ensure they contain only the 20 standard amino acids (ACDEFGHIKLMNPQRSTVWY). Remove invalid sequences and normalize remaining data.

In [19]:
import numpy as np

# Standard 20 amino acids
STD_AA = set('ACDEFGHIKLMNPQRSTVWY')

print(df.shape[0])

# Check each seq 
def check_sequence(seq):
    if pd.isna(seq):
        return False, set(), 'NaN'
    
    seq = str(seq).strip().upper()
    
    if len(seq) == 0:
        return False, set(), 'empty'
    
    # Unique characters in the sequence
    unique_chars = set(seq)
    
    # Check only standard aa
    valid_chars = unique_chars & STD_AA
    invalid_chars = unique_chars - STD_AA
    
    is_valid = len(invalid_chars) == 0
    
    status = 'OK' if is_valid else f' invalid: {invalid_chars}'
    
    return is_valid, invalid_chars, status

# Check each seq
results = df['Sequence'].apply(check_sequence)
df[['seq_valid', 'invalid_chars', 'seq_status']] = pd.DataFrame(results.tolist(), index=df.index)

# Statistics
print("\n Results:")
print(f" Valid Seq: {df['seq_valid'].sum()}")
print(f" Invalid: {df['seq_valid'].eq(False).sum()} ({100*(1-df['seq_valid'].mean()):.1f}%)")

# Show typical problems
invalid_df = df[~df['seq_valid']].copy()
if len(invalid_df) > 0:
    print("\n Top problems (first 10):")
    display_cols = ['APD ID', 'Sequence', 'seq_status', 'invalid_chars']
    print(invalid_df[display_cols].head(10).to_string(index=False))
    
    # Statistics on invalid characters
    all_invalid = set()
    for chars in invalid_df['invalid_chars']:
        all_invalid.update(chars)
    
    print(f"\n  FFound non-standard characters: {sorted(all_invalid)}")

# Filtering - only valid
df = df[df['seq_valid']].copy()

# normalization (upper case, strip)
df['Sequence'] = df['Sequence'].astype(str).str.strip().str.upper()


# final check
final_check = df['Sequence'].apply(lambda x: len(set(str(x)) - STD_AA) == 0).all()
print(f"All {df.shape[0]} sequences are clean!")



# Save Sequence
df.drop(['seq_valid', 'invalid_chars', 'seq_status'], axis=1, inplace=True, errors='ignore')
output_path = '../processed/apd6_cVAE.csv' 
df.to_csv(output_path, index=False)

5955

 Results:
 Valid Seq: 5955
 Invalid: 0 (0.0%)
All 5955 sequences are clean!

In [20]:

# Filter by Sequence Length (5-60 amino acids)
MIN_LENGTH = 5
MAX_LENGTH = 60

# Calculate sequence lengths
df['length'] = df['Sequence'].apply(len)

# Statistics before filtering
print(f"Before length filtering:")
print(f"  Total sequences: {df.shape[0]}")
print(f"  Length range: {df['length'].min()}-{df['length'].max()}")
print(f"  Length distribution:")
print(df['length'].describe())

# Apply length filter
df_filtered = df[(df['length'] >= MIN_LENGTH) & (df['length'] <= MAX_LENGTH)].copy()

# Statistics after filtering
removed_count = df.shape[0] - df_filtered.shape[0]
print(f"\nAfter length filtering ({MIN_LENGTH}-{MAX_LENGTH}):")
print(f"  Remaining sequences: {df_filtered.shape[0]}")
print(f"  Removed sequences: {removed_count} ({100*removed_count/df.shape[0]:.1f}%)")
print(f"  New length range: {df_filtered['length'].min()}-{df_filtered['length'].max()}")

# Drop the temporary length column and save
df_filtered.drop('length', axis=1, inplace=True)
output_path = '../processed/master_dataset.csv'
df_filtered.to_csv(output_path, index=False)
print(f"\nFiltered data saved to {output_path}")

# Update df to filtered version
df = df_filtered

Before length filtering:
  Total sequences: 5955
  Length range: 5-60
  Length distribution:
count    5955.000000
mean       23.951805
std        11.306411
min         5.000000
25%        14.000000
50%        21.000000
75%        31.000000
max        60.000000
Name: length, dtype: float64

After length filtering (5-60):
  Remaining sequences: 5955
  Removed sequences: 0 (0.0%)
  New length range: 5-60

Filtered data saved to ../processed/master_dataset.csv

In [21]:
df.head(5)

,APD ID,Sequence,Length,is_antibacterial,is_anti_gram_positive,is_anti_gram_negative,is_antifungal,is_antiviral,is_antiparasitic,is_anticancer
0,AP05452,AAAGKHKNKGKKNGKHNGWK,20.0,1,1,1,1,0,0,0
1,AP05433,AAAHKHGHGHGKHKNKGKKN,20.0,1,1,1,1,0,0,0
2,AP01515,AACSDRAHGHICESFKSFCKDSGRNGVKLRANCKKTCGLC,40.0,1,1,1,0,0,0,0
3,AP00612,AAEFPDFYDSEEQMGPHQEAEDEKDRADQRVLTEEEKKELENLAAM...,60.0,1,1,1,0,0,0,0
4,AP01914,AAFRGCWTKNYSPKPCL,17.0,1,1,0,0,0,0,0